### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by rvalyi** [akretion/l10n-brazil#10]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] l10n_br_account_product
- [ ] l10n_br_account_payment
- [ ] l10n_br_data_account
- [ ] l10n_br_account
- [ ] l10n_br_stock_account
- [ ] l10n_br_data_base
- [ ] l10n_br_crm_zip
- [ ] l10n_br_stock
- [ ] l10n_br_zip
- [ ] l10n_br_sale
- [ ] l10n_br_account_product_service
- [ ] l10n_br_sale_stock
- [ ] l10n_br_hr_timesheet_invoice
- [ ] l10n_br_purchase
- [ ] l10n_br_account_service
- [ ] l10n_br_data_account_product
- [ ] l10n_br_account_voucher
- [ ] l10n_br_delivery
- [ ] l10n_br_crm
- [ ] l10n_br_data_account_service
- [ ] l10n_br_base
- [ ] l10n_br_sale_service
- [ ] l10n_br_sale_product

**Comment by mileo** [comment]
@rvalyi Seria bacana fecharmos os PR antes de pensarmos na 9.0 
c.c: @danimaribeiro @renatonlima @sadamo
